### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by ONourry** [SANTOMY/PlaceIt#2]
As a user, I want to be able to create my profile, view my information and edit my information.

[Points: X]

[Value: High]

[Risk: Low]

Tasks
Front-End
- [x] Create UI to register (~X 時間), Points: X ,  Task ref: #8 
- [ ] Allow User to edit information (~X 時間), Points: X , Task ref: #9 
- [x] Create UI to view profile (~X 時間), Points: X , Task ref: #10  
- [x] Create UI to login (~X 時間), Points: X ,  Task ref: #30 

Back-End / Database
- [x] Implement Register User (~X 時間), Points: X , Task ref: #11 
- [x] Implement Edit Information functions (~X 時間), Points: X , Task ref: #25
- [x] Implement User object in the code (~X 時間), Points: X , Task ref: #12
