### ISSUE TITLE
Map Functionalities

### ISSUE THREAD

**Issue by ONourry** [SANTOMY/PlaceIt#5]
As a user, I want to be able to view spots on the map, filter spots and see spot details

[Points: X]

[Value: High]

[Risk: Low]

Tasks
Front-End
- [x] Create UI to show map (~X 時間), Points: X ,  Task ref: #17
- [x] Display spots on the map (~X 時間), Points: X , Task ref: #18 
- [x] Filter spots on the map (~X 時間), Points: X , Task ref: #20

Back-End / Database
- [x] Load spots from database (~X 時間), Points: X , Task ref: #21
- [x] Create filtering function (~X 時間), Points: X , Task ref: #22
