### ISSUE TITLE
Spot Functionalities

### ISSUE THREAD

**Issue by ONourry** [SANTOMY/PlaceIt#6]
As a user, I want to be able to create new spots, view their details and add review to existing spots

[Points: X]

[Value: High]

[Risk: Low]

Tasks
Front-End
- [x] View Spot details (~X 時間), Points: X ,  Task ref: #19
- [x] Create UI to register (~X 時間), Points: X , Task ref: #3
- [x] Review Spots (~X 時間), Points: X ,  Task ref: #23

Back-End / Database
- [x] Assign review to spot and create review in database (~X 時間), Points: X , Task ref: #24
- [x] Create new spot in database (~X 時間), Points: X , Task ref: #25
